# Dependencies
markdown:         redcarpet
highlighter:      pygments
baseurl: /

# Permalinks
permalink:        pretty

# Setup
title:            CNAQ
tagline:          '中文技术博客'
description:      '介绍国内外最新最前沿的前端开发技术。'
url:              http://www.cnaq.net
author:
  name:           '老超'
  url:            http://www.cnaq.net

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/laochao/cnaq
